name: Performance Test

on:
  pull_request:
  issue_comment:
  schedule:
  # don't know the timezone but it's daily at least
  - cron:  '0 7 * * *'

jobs:
  perf:
    name: Request per Second
    runs-on: ubuntu-20.04
    if: ${{ (github.event_name == 'pull_request' && startsWith(github.event.pull_request.title, 'perf(')) || github.event_name == 'schedule' || (github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.issue.body, '/perf')) }}

    steps:
    - uses: azure/docker-login@v1
      continue-on-error: true
      with:
        username: ${{ secrets.KONG_USERNAME }}
        password: ${{ secrets.KONG_PASSWORD }}

    - name: Checkout Kong source code
      uses: actions/checkout@v2
      # Fetch all history for all tags and branches
      with:
        fetch-depth: 0
    
    - name: Install OpenResty
      run: |
        sudo apt-get -y install --no-install-recommends wget gnupg ca-certificates
        wget -O - https://openresty.org/package/pubkey.gpg | sudo apt-key add -
        echo "deb http://openresty.org/package/ubuntu $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/openresty.list
        sudo apt-get update
        sudo apt install openresty

    - name: Install Dependencies
      run: |
        wget https://luarocks.org/releases/luarocks-3.7.0.tar.gz -O - |tar zxvf -
        pushd luarocks-*/
        ./configure --with-lua=/usr/local/openresty/luajit/ \
          --lua-suffix=jit \
          --with-lua-include=/usr/local/openresty/luajit/include/luajit-2.1
        sudo make install
        popd

        # just need the lua files to let all imports happy
        # the CI won't actually run Kong locally
        git clone https://github.com/kong/lua-kong-nginx-module /tmp/lua-kong-nginx-module
        pushd /tmp/lua-kong-nginx-module
        sudo make LUA_LIB_DIR=/usr/local/share/lua/5.1/ install
        popd

        # in Kong repository
        sudo apt install libyaml-dev -y
        sudo make dev

    - name: Run Tests
      env:
        PERF_TEST_VERSIONS: git:${{ github.sha }},git:master
      run: bin/busted -o gtest spec/04-perf/01-rps/ -t single_route

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: rps-and-latency.txt
        path: output/result.txt

    - name: Output
      id: output
      run: |
        result=$(cat output/result.txt)
        # https://github.community/t/set-output-truncates-multiline-strings/16852/2
        result="${result//'%'/'%25'}"
        result="${result//$'\n'/'%0A'}"
        result="${result//$'\r'/'%0D'}"

        echo ::set-output name=result::"$result"
    
    - name: Comment
      if: ${{ github.event_name == 'pull_request' }}
      uses: actions-ecosystem/action-create-comment@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        body: |
          :rocket: RPS and latency result compared to master:

          <details><summary>Click to expand</summary>

          ```
          ${{ steps.output.outputs.result }}
          ```

          </details>
